### ISSUE TITLE
Error when closing websocket connection

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#113]
```
2020-07-01 18:57:10 [critical ] [twisted] Unhandled Error
Traceback (most recent call last):
  File "/usr/src/app/hathor/cli/run_node.py", line 362, in run
    reactor.run()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1272, in run
    self.mainLoop()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1284, in mainLoop
    self.doIteration(t)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 627, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 255, in _disconnectSelectable
    selectable.connectionLost(f)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/local/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 288, in connectionLost
    self._connectionLost(reason)
  File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 2501, in _connectionLost
    WebSocketProtocol._connectionLost(self, reason)
  File "/usr/local/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1128, in _connectionLost
    self._onClose(self.wasClean, WebSocketProtocol.CLOSE_STATUS_CODE_ABNORMAL_CLOSE, "connection was closed uncleanly (%s)" % self.wasNotCleanReason)
  File "/usr/local/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 331, in _onClose
    self.onClose(wasClean, code, reason)
  File "/usr/src/app/hathor/websocket/protocol.py", line 28, in onClose
    self.factory.connection_closed(self)
  File "/usr/src/app/hathor/websocket/factory.py", line 321, in connection_closed
    self.connections.remove(connection)
builtins.KeyError: <hathor.websocket.protocol.HathorAdminWebsocketProtocol object at 0x7fdc268aebe0>
```

**Comment by jansegre** [comment]
I don't think this happens anymore.
