### ISSUE TITLE
Unhandled exception in a malformed Stratum packet

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#280]
It seems we just have to capture the `UnicodeDecodeError` here: https://github.com/HathorNetwork/hathor-core/blob/v0.40.2/hathor/stratum/stratum.py#L197-L201

```
  | 2021-07-28T08:22:57.818-07:00 | Traceback (most recent call last):
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
  | 2021-07-28T08:22:57.818-07:00 | return callWithContext({"system": lp}, func, *args, **kw)
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
  | 2021-07-28T08:22:57.818-07:00 | return context.call({ILogContext: newCtx}, func, *args, **kw)
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
  | 2021-07-28T08:22:57.818-07:00 | return self.currentContext().callWithContext(ctx, func, *args, **kw)
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
  | 2021-07-28T08:22:57.818-07:00 | return func(*args,**kw)
  | 2021-07-28T08:22:57.818-07:00 | --- <exception caught here> ---
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
  | 2021-07-28T08:22:57.818-07:00 | why = selectable.doRead()
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
  | 2021-07-28T08:22:57.818-07:00 | return self._dataReceived(data)
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
  | 2021-07-28T08:22:57.818-07:00 | rval = self.protocol.dataReceived(data)
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
  | 2021-07-28T08:22:57.818-07:00 | why = self.lineReceived(line)
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/hathor/stratum/stratum.py", line 198, in lineReceived
  | 2021-07-28T08:22:57.818-07:00 | data = json_loadb(line)
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/site-packages/hathor/util.py", line 217, in json_loadb
  | 2021-07-28T08:22:57.818-07:00 | return json.loads(raw)
  | 2021-07-28T08:22:57.818-07:00 | File "/usr/local/lib/python3.7/json/__init__.py", line 343, in loads
  | 2021-07-28T08:22:57.818-07:00 | s = s.decode(detect_encoding(s), 'surrogatepass')
  | 2021-07-28T08:22:57.818-07:00 | builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 4: invalid start byte
```

**Comment by msbrogli** [comment]
It seems `json.loads(x)` assumes `x` is either UTF-8, UTF-16, or UTF-32.

Link: https://docs.python.org/3/library/json.html#json.loads

**Comment by msbrogli** [comment]
I checked that some calls to `json.loads(...)` are not handling exceptions properly. Anyway, I feel this diff should solve the issue:

```
diff --git a/hathor/util.py b/hathor/util.py
index 243a8b29..a4f7ea2b 100644
--- a/hathor/util.py
+++ b/hathor/util.py
@@ -215,7 +215,10 @@ def json_loadb(raw: bytes) -> Dict:

     # XXX: from Python3.6 onwards, json.loads can take bytes
     #      See: https://docs.python.org/3/library/json.html#json.loads
-    return json.loads(raw)
+    try:
+        return json.loads(raw)
+    except UnicodeDecodeError as exc:
+        raise JSONDecodeError from exc
```

**Comment by luislhl** [comment]
It seems we are getting this yet, even after the v0.41.0 release.
I'll reopen this for further investigation.

**Comment by jansegre** [comment]
This has been implemented.
