### ISSUE TITLE
Error: failed to parse whitelist

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-core#301]
I spotted this error in one of our full-nodes.

The log message says what is in the title: `failed to parse whitelist`.

There is also this Traceback:
```
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/hathor/p2p/manager.py", line 336, in _update_whitelist_cb
   new_whitelist = parse_whitelist(text)
 File "/usr/local/lib/python3.7/site-packages/hathor/p2p/utils.py", line 186, in parse_whitelist
   lines = parse_file(text, header=header)
 File "/usr/local/lib/python3.7/site-packages/hathor/p2p/utils.py", line 162, in parse_file
   raise ValueError('invalid header')
ValueError: invalid header
```

The solution would be to probably improve exception treatment when making the request to get the whitelist. 

Sometimes we also get a `update whitelist failed` which is probably related:

```
{'args': ['<twisted.python.failure.Failure twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.ZeroReturnError: >]>'], 'kwargs': {}} 
```

**Comment by jansegre** [comment]
Probably does not apply anymore.
