### ISSUE TITLE
RuntimeError: Request.finish called on a request after its connection was lost

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-core#303]
Error detected in our testnet full-nodes. It's possible that it also happens in mainnet ones.

```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/usr/local/lib/python3.7/site-packages/hathor/transaction/resources/graphviz.py", line 81, in _err_tx_resolve
request.processingFailed(reason)
File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 414, in processingFailed
self.finish()
File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 286, in finish
return http.Request.finish(self)
File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1080, in finish
"Request.finish called on a request after its connection was lost; "
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

**Comment by jansegre** [comment]
This hasn't happened in a while as far as I can tell.
