### ISSUE TITLE
Error: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-core#304]
There is an exception being generated when the websocket connection is closed uncleanly.

```
{"reason": "connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)", "event": "connection closed", "logger": "hathor.websocket.protocol", "level": "info", "timestamp": "2021-09-02 17:52:28"}
/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py:290:dataReceived
/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py:1207:_dataReceived
/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py:1219:consumeData
/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py:1579:processData
/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py:1704:onFrameEnd
/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py:318:_onMessageEnd
/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py:628:onMessageEnd
/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py:321:_onMessage
/usr/local/lib/python3.7/site-packages/hathor/websocket/protocol.py:49:onMessage
/usr/local/lib/python3.7/site-packages/hathor/websocket/factory.py:301:handle_message
/usr/local/lib/python3.7/json/__init__.py:348:loads
/usr/local/lib/python3.7/json/decoder.py:337:decode
/usr/local/lib/python3.7/json/decoder.py:355:raw_decode
]
why None
isError 1
message ()
time 1630605135.4414759
log_time 1630605135.4414759
log_text Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
return callWithContext({"system": lp}, func, *args, **kw)
File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
return context.call({ILogContext: newCtx}, func, *args, **kw)
File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)
File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
return func(*args,**kw)
--- <exception caught here> ---
File "/usr/local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
why = selectable.doRead()
File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
return self._dataReceived(data)
File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
rval = self.protocol.dataReceived(data)
File "/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
self._dataReceived(data)
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1207, in _dataReceived
self.consumeData()
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1219, in consumeData
while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1579, in processData
fr = self.onFrameEnd()
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1704, in onFrameEnd
self._onMessageEnd()
File "/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py", line 318, in _onMessageEnd
self.onMessageEnd()
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 628, in onMessageEnd
self._onMessage(payload, self.message_is_binary)
File "/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py", line 321, in _onMessage
self.onMessage(payload, isBinary)
File "/usr/local/lib/python3.7/site-packages/hathor/websocket/protocol.py", line 49, in onMessage
self.factory.handle_message(self, payload)
File "/usr/local/lib/python3.7/site-packages/hathor/websocket/factory.py", line 301, in handle_message
message = json.loads(data)
File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
log_format {log_text}
log_level <LogLevel=critical>
log_namespace log_legacy
log_system _GenericHTTPChannelProtocol,5762676,172.17.0.4
format %(log_legacy)s
log_legacy Unhandled Error
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
return callWithContext({"system": lp}, func, *args, **kw)
File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
return context.call({ILogContext: newCtx}, func, *args, **kw)
File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)
File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
return func(*args,**kw)
--- <exception caught here> ---
File "/usr/local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
why = selectable.doRead()
File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
return self._dataReceived(data)
File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
rval = self.protocol.dataReceived(data)
File "/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
self._dataReceived(data)
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1207, in _dataReceived
self.consumeData()
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1219, in consumeData
while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1579, in processData
fr = self.onFrameEnd()
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 1704, in onFrameEnd
self._onMessageEnd()
File "/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py", line 318, in _onMessageEnd
self.onMessageEnd()
File "/usr/local/lib/python3.7/site-packages/autobahn/websocket/protocol.py", line 628, in onMessageEnd
self._onMessage(payload, self.message_is_binary)
File "/usr/local/lib/python3.7/site-packages/autobahn/twisted/websocket.py", line 321, in _onMessage
self.onMessage(payload, isBinary)
File "/usr/local/lib/python3.7/site-packages/hathor/websocket/protocol.py", line 49, in onMessage
self.factory.handle_message(self, payload)
File "/usr/local/lib/python3.7/site-packages/hathor/websocket/factory.py", line 301, in handle_message
message = json.loads(data)
File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
error when logging event '"system"'
system _GenericHTTPChannelProtocol,5762990,172.17.0.4
error when logging event '"system"'
system _GenericHTTPChannelProtocol,5762676,172.17.0.4
failure [Failure instance: Traceback: <class 'json.decoder.JSONDecodeError'>: Expecting value: line 1 column 1 (char 0)
/usr/local/lib/python3.7/site-packages/twisted/python/log.py:103:callWithLogger
/usr/local/lib/python3.7/site-packages/twisted/python/log.py:86:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:85:callWithContext
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/internet/posixbase.py:614:_doReadOrWrite
/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py:243:doRead
/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py:249:_dataReceived
```

Check it on CloudWatch: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E$25272021-09-02T17*3a52*3a32.549Z$257Estart$257E$25272021-09-02T17*3a52*3a25.598Z$257EtimeType$257E$2527ABSOLUTE$257Etz$257E$2527Local$257EeditorString$257E$2527fields*20*40timestamp*2c*20*40message*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*20200$257EisLiveTail$257Efalse$257EqueryId$257E$2527de503e4e-31b5-4758-b010-b54233465ec2$257Esource$257E$2528$257E$2527*2fhathor*2fecs*2fcontainer-logs*2ftestnet*2ffull-node$2529$2529

**Comment by jansegre** [comment]
This hasn't happened recently as far as I can tell.
