### ISSUE TITLE
KeyError: 'unknown token'

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-core#378]
This error happens in the decode_tx api.

We should just catch the error and return it in the API.

```
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 235, in process
   self.render(resrc)
 File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 302, in render
   body = resrc.render(self)
 File "/usr/local/lib/python3.7/site-packages/twisted/web/resource.py", line 265, in render
   return m(request)
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/resources/decode_tx.py", line 58, in render_GET
   data = get_tx_extra_data(tx)
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/resources/transaction.py", line 116, in get_tx_extra_data
   token_info = tokens_index.get_token_info(bytes.fromhex(token_uid_hex))
 File "/usr/local/lib/python3.7/site-packages/hathor/indexes/memory_tokens_index.py", line 166, in get_token_info
   raise KeyError('unknown token')
KeyError: 'unknown token'
```

**Comment by jansegre** [comment]
True, this endpoint seems to return 500 on some invalid inputs, it could be simply decorated with `@api_catch_exceptions`.
