### ISSUE TITLE
hathor.transaction.storage.exceptions.TransactionDoesNotExist

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-core#381]
We are getting this exception logged as critical level.

Maybe we should just treat the error and return in the API.
If we want it logged, we should change the log level to info.

```
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 235, in process
   self.render(resrc)
 File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 302, in render
   body = resrc.render(self)
 File "/usr/local/lib/python3.7/site-packages/twisted/web/resource.py", line 265, in render
   return m(request)
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/resources/push_tx.py", line 192, in render_POST
   ret = self.handle_push_tx(data, self._get_client_ip(request))
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/resources/push_tx.py", line 98, in handle_push_tx
   is_double_spending = tx.is_double_spending()
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/transaction.py", line 551, in is_double_spending
   tx = self.storage.get_transaction(tx_in.tx_id)
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/storage/transaction_storage.py", line 481, in get_transaction
   tx = self._get_transaction(hash_bytes)
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/storage/cache_storage.py", line 181, in _get_transaction
   tx = self.store.get_transaction(hash_bytes)
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/storage/transaction_storage.py", line 483, in get_transaction
   tx = self._get_transaction(hash_bytes)
 File "/usr/local/lib/python3.7/site-packages/hathor/transaction/storage/rocksdb_storage.py", line 145, in _get_transaction
   raise TransactionDoesNotExist(hash_bytes.hex())
hathor.transaction.storage.exceptions.TransactionDoesNotExist: 0000033139d08176d1051fb3a272c3610457f0c7f686afbe0afe3d37f966db85
```

**Comment by jansegre** [comment]
This hasn't happened anymore, although this could be forced with invalid inputs, but there's no negative side effects.
