### ISSUE TITLE
`create_tx` API assumes the value is an integer and raises an Error when it's a string

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-core#417]
Error:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 229, in process
self.render(resrc)
File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 294, in render
body = resrc.render(self)
File "/usr/local/lib/python3.7/site-packages/twisted/web/resource.py", line 263, in render
return m(request)
File "/usr/local/lib/python3.7/site-packages/hathor/util.py", line 289, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/hathor/transaction/resources/create_tx.py", line 76, in render_POST
outputs = [from_raw_output(i, tokens) for i in raw_outputs]
File "/usr/local/lib/python3.7/site-packages/hathor/transaction/resources/create_tx.py", line 76, in <listcomp>
outputs = [from_raw_output(i, tokens) for i in raw_outputs]
File "/usr/local/lib/python3.7/site-packages/hathor/transaction/resources/create_tx.py", line 43, in from_raw_output
return TxOutput(value, script, token_data)
File "/usr/local/lib/python3.7/site-packages/hathor/transaction/base_transaction.py", line 1146, in __init__
assert isinstance(value, int), 'value is %s, type %s' % (str(value), type(value))
AssertionError: value is 10, type <class 'str'>
```

**Comment by jansegre** [comment]
What is the expected behavior? I think it should return a proper 409 error code, that is not what happens, right?

**Comment by jansegre** [comment]
This endpoint already has a `@api_catch_exceptions` to return proper errors.
